first
chugunse/java-filmorate pull request #2
Opened 2022-12-13 10:43 UTC by chugunse

2022-12-14 10:07 UTC, AnastasiyaFomkina requested changes

2022-12-14 10:07 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        LocalDate birthday = LocalDate.parse(user.getBirthday(), inputFormatter);
[@PastOrPresent](https://docs.jboss.org/hibernate/beanvalidation/spec/2.0/api/javax/validation/constraints/PastOrPresent.html)

2022-12-14 10:07 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    static Film testFilm;
`static` с полями класса нужно использовать только в том случае, когда к нему нужен глобальный доступ (например - константное значение), в любом другом случае - это становится небезопасно

Удали, пожалуйста, у всех полей в тестах

2022-12-14 10:07 UTC, AnastasiyaFomkina commented on src/test/java/ru/yandex/practicum/filmorate/controller/FilmControllerTest.java
> +    public void validationBadFilm() {
Лучше разбить один большой тест на несколько маленьких, так его будет проще поддерживать и будет легче отлавливать ошибки в работе программы

2022-12-14 10:39 UTC, chugunse commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isEmpty()) {
там в задании зачем то просили сначала сделать так, а потом добавить проверку анотациями, а после вообще тесты зачем то по первой проверке
а вот как сделать тесты самого контроллера мне вообще не понятно(((((

2022-12-15 15:57 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isEmpty()) {
Двойную работу точно делать не нужно :)

Тесты нужно писать не на контроллер, а на валидациию. Просто нужно проверить, что поля корректно валидируются

2022-12-21 08:12 UTC, AnastasiyaFomkina approved these changes

2022-12-21 08:12 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        LocalDate birthday = LocalDate.parse(user.getBirthday(), inputFormatter);
День рождения лучше тоже валидировать с помощью спринговой валидации, а не руками

2022-12-21 08:12 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
👍

2022-12-21 08:12 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
👍

2023-01-18 16:29 UTC, merged