Add database
chugunse/java-filmorate pull request #4
Opened 2023-01-18 12:46 UTC by chugunse

2023-01-18 17:49 UTC, AnastasiyaFomkina requested changes
Нужно удалить классы старых реализаций, а не комментировать их:
`src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java`
`src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java`

И добавить тесты, которые требуются в тз

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("filmDbStorage")
Нужно удалить во всех сервисах `@Autowired` и `@Qualifier`, так как они не нужны.

_Чуть-чуть теории:_

`@Qualifier` используется только когда у нас есть несколько реализаций одного интерфейса, а так как старые интерфейсы у тебя закомментированы, смысла в нем нет.
А еще `Spring` умный и может подтягивать нужную реализацию, если название указать ровно такое же, как и у класса, который мы хотим использовать, только с маленькой буквы: 

`private final FilmStorage filmDbStorage;`

Но опять же, так как у нас всего одна реализация интерфейса `FilmStorage`, это делать не нужно

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        film.setId(generatedId.getKey().intValue());
Прежде чем получать значение методом `.intValue()`, нужно проверить, что результат операции `generatedId.getKey()` не равен `null`, иначе получим неприятную `NullPointerException`

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        user.setId(generatedId.getKey().intValue());
Тоже нужно сначала проверить на `null`, как в классе `FilmDbStorage`

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +//                "WHERE fg.film_id = ?";
Весь закомментированный код нужно удалить

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String checkQuery = "SELECT * FROM films WHERE id = ?";
Все дублирующиеся запросы, лучше вынести в константы

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private void checkFilmAndUser(int filmId, int userId) {
Лучше вынести логику взаимодействия с пользователями в сервис. Вместо того, чтобы создавать дублирующий зарос к базе, можно использовать метод `ru.yandex.practicum.filmorate.storage.user.UserDbStorage#getById` и, в нужных местах, сначала проверять, получили ли мы пользователя с таким id, а потом уже идти в хранилище

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        SqlRowSet userRowsRevers = jdbcTemplate.queryForRowSet(checkQuery, secondId, firstId);
А зачем нужен этот вызов, если результат, полученный из базы никак дальше не используется?

2023-01-18 17:49 UTC, AnastasiyaFomkina commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +    private User makeUser(ResultSet rs, int rowNum) throws SQLException {
Лучше не сокращать названия параметров
```suggestion
    private User makeUser(ResultSet resultSet, int rowNum) throws SQLException {
```

2023-01-19 13:23 UTC, chugunse commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jpa</artifactId>
после этого в коде идея перестает видеть таблицы в sql запросах 
точнее выделяет красным названия таблиц в запросах

2023-01-19 13:25 UTC, chugunse commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    @Qualifier("filmDbStorage")
нам зачем то в ТЗ об этом сказали, и я просто решил испробовать этот инструмент, удобно
естественно я понимал, что он в данной реализации не нужен )))

2023-01-19 13:45 UTC, chugunse commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        String checkQuery = "SELECT * FROM films WHERE id = ?";
мне кажется это снизит читаемость кода, удобно когда у каждого метода написан внутри именно свой запрос

2023-01-20 12:47 UTC, AnastasiyaFomkina approved these changes

2023-01-20 12:49 UTC, merged